name: Convert GFW Rules

on:
  schedule:
    - cron: '0 0 * * *'  # 每小时运行一次，抓取最新的 gfw.txt 并进行转换
  workflow_dispatch:  # 允许手动触发工作流
  push:
    paths:
      - '.github/workflows/convert-gfw.yml'  # 监控工作流文件的更新

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download gfw.txt from GitHub
      run: |
        curl -O https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/gfw.txt

    - name: Convert gfw.txt to gfw-ok.txt (Adblock Plus format)
      run: |
        python3 convert_gfw_to_adblock.py

    - name: Set up Git for pushing changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

    - name: Commit and push converted gfw-ok.txt
      run: |
        git add gfw-ok.txt
        git add gfw-ok-base64.txt
        git commit -m "Update gfw-ok.txt"
        git push